### ISSUE TITLE
Prognostic run diags step erroring on 3D output variables

### ISSUE THREAD

**Issue by brianhenn** [VulcanClimateModeling/fv3net#1099]
Prognostic run diagnostics workflow is failing on master when run against output from a nudge-to-fine run with typical diagnostic outputs.  This looks to be because #1082 in interpolating 3D diagnostics to reference pressure levels assumes vcm defaults about dimension names that are not true for outputs from the wrapper, e.g., the 3D variables saved in `state_after_timestep.zarr`. The steps's 3D interpolation routine needs flexibility to handle different dataset dimensions.

fv3net commit: 5d062242642e0bfddb61995fdf52e597d02fca60

Trace:
```
 prognostic_run_diags save gs://vcm-ml-experiments/2021-03-17-rad-flux-setting/nudge-to-fine-run diags.nc
No prognostic run diagnostics detected in cache for given run. Computing diagnostics and adding to cache.
/opt/conda/envs/fv3net/lib/python3.7/site-packages/intake/__init__.py:39: UserWarning: deprecation: intake.Catalog now references the base class intake.catalog.base.Catalog
 If you want to open a generic URL, you should use intake.open_catalog
  warnings.warn('deprecation: intake.Catalog now references the base class intake.catalog.base.Catalog\n '
/opt/conda/envs/fv3net/lib/python3.7/site-packages/intake/__init__.py:39: UserWarning: deprecation: intake.Catalog now references the base class intake.catalog.base.Catalog
 If you want to open a generic URL, you should use intake.open_catalog
  warnings.warn('deprecation: intake.Catalog now references the base class intake.catalog.base.Catalog\n '
INFO:fv3net.diagnostics.prognostic_run.load_diagnostic_data:Processing dycore data from run directory at gs://vcm-ml-experiments/2021-03-17-rad-flux-setting/nudge-to-fine-run
INFO:fv3net.diagnostics.prognostic_run.load_diagnostic_data:Opening Grid Spec
INFO:fv3net.diagnostics.prognostic_run.load_diagnostic_data:Opening verification data
INFO:fv3net.diagnostics.prognostic_run.load_diagnostic_data:Opening prognostic run data at gs://vcm-ml-experiments/2021-03-17-rad-flux-setting/nudge-to-fine-run/atmos_dt_atmos.zarr
INFO:fv3net.diagnostics.prognostic_run.load_diagnostic_data:Loading and standardizing gs://vcm-ml-experiments/2021-03-17-rad-flux-setting/nudge-to-fine-run/atmos_dt_atmos.zarr
INFO:fv3net.diagnostics.prognostic_run.load_diagnostic_data:Processing physics data from run directory at gs://vcm-ml-experiments/2021-03-17-rad-flux-setting/nudge-to-fine-run
INFO:fv3net.diagnostics.prognostic_run.load_diagnostic_data:Opening Grid Spec
INFO:fv3net.diagnostics.prognostic_run.load_diagnostic_data:Opening prognostic run data at gs://vcm-ml-experiments/2021-03-17-rad-flux-setting/nudge-to-fine-run
INFO:fv3net.diagnostics.prognostic_run.load_diagnostic_data:Loading and standardizing gs://vcm-ml-experiments/2021-03-17-rad-flux-setting/nudge-to-fine-run/sfc_dt_atmos.zarr
INFO:fv3net.diagnostics.prognostic_run.load_diagnostic_data:Loading and standardizing gs://vcm-ml-experiments/2021-03-17-rad-flux-setting/nudge-to-fine-run/diags.zarr
INFO:fv3net.diagnostics.prognostic_run.load_diagnostic_data:Processing 3d data from run directory at gs://vcm-ml-experiments/2021-03-17-rad-flux-setting/nudge-to-fine-run
INFO:fv3net.diagnostics.prognostic_run.load_diagnostic_data:Loading and standardizing gs://vcm-ml-experiments/2021-03-17-rad-flux-setting/nudge-to-fine-run/state_after_timestep.zarr
INFO:fv3net.diagnostics.prognostic_run.load_diagnostic_data:Opening Grid Spec
Traceback (most recent call last):
  File "/opt/conda/envs/fv3net/bin/prognostic_run_diags", line 33, in <module>
    sys.exit(load_entry_point('fv3net-diagnostics-prog-run', 'console_scripts', 'prognostic_run_diags')())
  File "/home/jovyan/fv3net/workflows/prognostic_run_diags/fv3net/diagnostics/prognostic_run/cli.py", line 29, in main
    args.func(dissoc(args, "func"))
  File "/home/jovyan/fv3net/workflows/prognostic_run_diags/fv3net/diagnostics/prognostic_run/compute.py", line 539, in main
    "3d": load_diags.load_3d(args.url, verif_entries["3d"], catalog),
  File "/home/jovyan/fv3net/workflows/prognostic_run_diags/fv3net/diagnostics/prognostic_run/load_diagnostic_data.py", line 127, in load_3d
    field=ds[var], delp=ds["pressure_thickness_of_atmospheric_layer"]
  File "/home/jovyan/fv3net/external/vcm/vcm/interpolate.py", line 75, in interpolate_to_pressure_levels
    levels, vcm.calc.thermo.pressure_at_midpoint_log(delp, dim=dim), field, dim=dim,
  File "/home/jovyan/fv3net/external/vcm/vcm/calc/thermo.py", line 148, in pressure_at_midpoint_log
    delp, toa_pressure=toa_pressure, dim_center=dim, dim_outer=dim
  File "/home/jovyan/fv3net/external/vcm/vcm/calc/thermo.py", line 51, in pressure_at_interface
    top = xr.full_like(delp.isel({dim_center: [0]}), toa_pressure).variable
  File "/opt/conda/envs/fv3net/lib/python3.7/site-packages/xarray/core/dataarray.py", line 1053, in isel
    variable = self._variable.isel(indexers, missing_dims=missing_dims)
  File "/opt/conda/envs/fv3net/lib/python3.7/site-packages/xarray/core/variable.py", line 1071, in isel
    indexers = drop_dims_from_indexers(indexers, self.dims, missing_dims)
  File "/opt/conda/envs/fv3net/lib/python3.7/site-packages/xarray/core/utils.py", line 767, in drop_dims_from_indexers
    f"dimensions {invalid} do not exist. Expected one or more of {dims}"
ValueError: dimensions {'pfull'} do not exist. Expected one or more of ('time', 'tile', 'z', 'y', 'x')
```

**Comment by brianhenn** [comment]
I specified the vertical dim name in the interpolation function call, which fixes the bug though the result is now an OOM on the 40-day nudged run ds (logs: https://gist.github.com/brianhenn/025ef0ca3bb3de6dc92e09c179b1dbd9)

**Comment by AnnaKwa** [comment]
Resolved by https://github.com/VulcanClimateModeling/fv3net/commit/20b903bd5f71efb17dad4abdf0ff95cb0a6dd1ed
