### ISSUE TITLE
nudge to fine routine fails on subtiles

### ISSUE THREAD

**Issue by brianhenn** [VulcanClimateModeling/fv3net#1105]
In trying to test whether the prephysics prescribed state setting works on multiple processes per tile, I discovered that the nudge-to-fine routine actually doesn't allow that. It's likely the case that the reference states are set at the dataset dimensions, e.g. 48x48, whereas the model states are subtiled. Not clear why this is the case since `fv3gfs.util.open_restart` handles non 1x1 layouts. Presumably we'd want to be able to have multiple processes per tile for N2F C96/C384 coarse model runs.

```
Traceback (most recent call last):
  File "/fv3net/workflows/prognostic_c48_run/sklearn_runfile.py", line 50, in <module>
    for time, diagnostics in loop:
  File "/fv3net/workflows/prognostic_c48_run/runtime/loop.py", line 486, in __iter__
    diagnostics.update(substep())
  File "/fv3net/workflows/prognostic_c48_run/runtime/loop.py", line 421, in _compute_postphysics
    ) = self._postphysics_stepper(self._state.time, self._state)
  File "/fv3net/workflows/prognostic_c48_run/runtime/steppers/nudging.py", line 43, in __call__
    tendencies = get_nudging_tendency(state, reference, self._nudging_timescales)
  File "/fv3net/workflows/prognostic_c48_run/runtime/nudging.py", line 231, in get_nudging_tendency
    return_data = (var_reference - var_state) / timescale.total_seconds()
  File "/usr/local/lib/python3.6/dist-packages/xarray/core/dataarray.py", line 2685, in func
    self, other = align(self, other, join=align_type, copy=False)
  File "/usr/local/lib/python3.6/dist-packages/xarray/core/alignment.py", line 327, in align
    % (dim, sizes)
ValueError: arguments without labels along dimension 'y' cannot be aligned because they have different dimension sizes: {24, 48}
```

**Comment by brianhenn** [comment]
Update: It's a bug due to a discrepancy between the wrapper and the open restart routine disagreeing on dimension order:

```
DEBUG:runtime.nudging:nudging state: <xarray.DataArray (z: 79, y: 48, x: 24)>
...
DEBUG:runtime.nudging:nudging reference state: <xarray.DataArray (z: 79, y: 24, x: 48)>
```

**Comment by oliverwm1** [comment]
Are you doing a 2x1 layout? fv3gsf-util does not properly support non-square layouts. See: https://github.com/VulcanClimateModeling/fv3gfs-util/issues/58

I'd be curious to know if you have issues with 2x2.

**Comment by brianhenn** [comment]
Yup thanks, looks like the 2x2 layout runs OK. Will close this since it's a duplicate.
