### ISSUE TITLE
Integration tests/prognostic run broken

### ISSUE THREAD

**Issue by nbren12** [VulcanClimateModeling/fv3net#1358]
06934dc6494cd282cb404b3624c084292a1329f4 broke the integration tests. The logs were a bit tricky to track down (had to look in gs://vcm-ml-scratch/test-end-to-end-integration/2021-09-15/39b4fcd-e96a-nudge-to-fine-run/fv3gfs_run/artifacts/20160801.001500/logs.txt), but this is the error:
```
KeyError: 'pressure_thickness_of_atmospheric_layer'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/usr/local/lib/python3.6/dist-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/fv3net/workflows/prognostic_c48_run/runtime/main.py", line 48, in <module>
    for time, diagnostics in loop:
  File "/fv3net/workflows/prognostic_c48_run/runtime/loop.py", line 475, in __iter__
    diagnostics.update(substep())
  File "/fv3net/workflows/prognostic_c48_run/runtime/loop.py", line 404, in _compute_postphysics
    self._state.time, self._state
  File "/fv3net/workflows/prognostic_c48_run/runtime/steppers/nudging.py", line 49, in __call__
    tendencies = get_nudging_tendency(state, reference, self._nudging_timescales)
  File "/fv3net/workflows/prognostic_c48_run/runtime/nudging.py", line 234, in get_nudging_tendency
    return_dict[STATE_NAME_TO_TENDENCY[name]] = return_data
KeyError: 'pressure_thickness_of_atmospheric_layer'
```
I'm surprised this didn't cause any errors in the regression tests. If possible, we should modify the nudging configuration to more closely match the integration tests, so that we can catch this earlier.

cc @AnnaKwa

**Comment by AnnaKwa** [comment]
Fixed by PR https://github.com/VulcanClimateModeling/fv3net/pull/1359
