### ISSUE TITLE
zarr monitor fails on write of time-interpolated D-grid winds in N2F runfile case

### ISSUE THREAD

**Issue by brianhenn** [VulcanClimateModeling/fv3net#938]
This appears to be a rather complex interaction between the zarr monitor and the fv3net `sklearn_runfile`'s N2F time-interpolation function. The run fails with an array size error (see below) when writing the time-interpolated reference state D-grid winds to `reference_state.zarr`, on the 2nd timestep. This error does NOT occur if a) no D-grid winds are being written to `reference_state.zarr` or b) no time interpolation of the nudging reference state is performed, so it's clearly related to interpolation. Additionally from what I can tell the error is occurring only on the non-zero rank processes because my attempt at debugging it by tracing output from `rank==0` showed that the zarr monitor write completed successfully, and the error messages come from the 5 non-zero ranks.

With the following user config:
```
base_version: v0.5
nudging:
  timescale_hours:
    air_temperature: 12
    specific_humidity: 12
    x_wind: 12
    y_wind: 12
    pressure_thickness_of_atmospheric_layer: 12
  reference_initial_time: "20160801.001500"
  reference_frequency_seconds: 3600
namelist:
  coupler_nml:
    current_date:
    - 2016
    - 8
    - 1
    - 0
    - 15
    - 0
    days: 0
    hours: 4
    minutes: 0
    months: 0
    seconds: 0
  fv_core_nml:
    do_sat_adj: false
  gfdl_cloud_microphysics_nml:
    fast_sat_adj: false
```

the following error results:

```
DEBUG:runtime.steppers.base:Physics Step (apply)
 ---isec,seconds         900         900
  gfs diags time since last bucket empty:   0.25000000000000000      hrs
 calculating slp kr value
 calculating slp kr value
DEBUG:runtime.steppers.base:Computing nudging tendencies
 calculating slp kr value
 calculating slp kr value
 calculating slp kr value
 calculating slp kr value
DEBUG:google.auth._default:Checking /key.json for explicit credentials as part of auth process...
DEBUG:google.auth._default:Checking /key.json for explicit credentials as part of auth process...
DEBUG:gcsfs.core:Connected with method google_default
DEBUG:gcsfs.core:Connected with method google_default
DEBUG:google.auth._default:Checking /key.json for explicit credentials as part of auth process...
DEBUG:google.auth._default:Checking /key.json for explicit credentials as part of auth process...
DEBUG:google.auth._default:Checking /key.json for explicit credentials as part of auth process...
DEBUG:gcsfs.core:Connected with method google_default
DEBUG:gcsfs.core:Connected with method google_default
DEBUG:google.auth._default:Checking /key.json for explicit credentials as part of auth process...
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:gcsfs.core:Connected with method google_default
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:gcsfs.core:Connected with method google_default
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:runtime.steppers.base:Getting state variables: ['air_temperature', 'pressure_thickness_of_atmospheric_layer', 'specific_humidity', 'x_wind', 'y_wind', 'total_precipitation', 'surface_precipitation_rate', 'pressure_thickness_of_atmospheric_layer']
DEBUG:runtime.steppers.base:Setting Fortran State
INFO:__main__:diags: ['storage_of_specific_humidity_path_due_to_microphysics', 'evaporation', 'cnvprcp_after_physics', 'total_precip_after_physics', 'tendency_of_specific_humidity_due_to_fv3_physics', 'tendency_of_air_temperature_due_to_fv3_physics', 'tendency_of_eastward_wind_due_to_fv3_physics', 'tendency_of_northward_wind_due_to_fv3_physics', 'storage_of_specific_humidity_path_due_to_fv3_physics', 'storage_of_total_water_path_due_to_fv3_physics', 'storage_of_mass_due_to_fv3_physics', 'air_temperature_reference', 'specific_humidity_reference', 'surface_temperature_reference', 'pressure_thickness_of_atmospheric_layer_reference', 'y_wind_reference', 'x_wind_reference', 'area', 'cnvprcp_after_python', 'total_precip', 'net_moistening_due_to_nudging', 'net_heating_due_to_nudging', 'water_vapor_path', 'physics_precip', 'net_mass_tendency_due_to_nudging', 'air_temperature_tendency_due_to_nudging', 'pressure_thickness_of_atmospheric_layer_tendency_due_to_nudging', 'specific_humidity_tendency_due_to_nudging', 'x_wind_tendency_due_to_nudging', 'y_wind_tendency_due_to_nudging', 'x_wind', 'y_wind', 'eastward_wind', 'northward_wind', 'vertical_wind', 'air_temperature', 'specific_humidity', 'pressure_thickness_of_atmospheric_layer', 'vertical_thickness_of_atmospheric_layer', 'land_sea_mask', 'surface_temperature', 'surface_geopotential', 'sensible_heat_flux', 'latent_heat_flux', 'total_precipitation', 'surface_precipitation_rate', 'total_soil_moisture', 'total_sky_downward_shortwave_flux_at_surface', 'total_sky_upward_shortwave_flux_at_surface', 'total_sky_downward_longwave_flux_at_surface', 'total_sky_upward_longwave_flux_at_surface', 'total_sky_downward_shortwave_flux_at_top_of_atmosphere', 'total_sky_upward_shortwave_flux_at_top_of_atmosphere', 'total_sky_upward_longwave_flux_at_top_of_atmosphere', 'clear_sky_downward_shortwave_flux_at_surface', 'clear_sky_upward_shortwave_flux_at_surface', 'clear_sky_downward_longwave_flux_at_surface', 'clear_sky_upward_longwave_flux_at_surface', 'clear_sky_upward_shortwave_flux_at_top_of_atmosphere', 'clear_sky_upward_longwave_flux_at_top_of_atmosphere', 'latitude', 'longitude', 'tendency_of_specific_humidity_due_to_python', 'tendency_of_air_temperature_due_to_python', 'tendency_of_eastward_wind_due_to_python', 'tendency_of_northward_wind_due_to_python', 'storage_of_specific_humidity_path_due_to_python', 'storage_of_total_water_path_due_to_python', 'storage_of_mass_due_to_python']
INFO:statistics:{"time": "2016-08-01T00:30:00", "storage_of_specific_humidity_path_due_to_microphysics": 3.514122620263514e-05, "evaporation": 3.556450552870381e-05, "cnvprcp_after_physics": 1.404243820461793e-05, "total_precip_after_physics": 1.5856664030241084e-05, "storage_of_specific_humidity_path_due_to_fv3_physics": 4.274285681870165e-05, "storage_of_total_water_path_due_to_fv3_physics": 1.843891007951917e-05, "storage_of_mass_due_to_fv3_physics": 0.00018088570788009033, "surface_temperature_reference": 290.1222061181736, "area": 38505756482.50796, "cnvprcp_after_python": 1.404243820461793e-05, "total_precip": 1.6508798317962014e-05, "net_moistening_due_to_nudging": -5.272274840053458e-07, "net_heating_due_to_nudging": 2.033826632857872, "water_vapor_path": 27.468113049104364, "physics_precip": 1.761851558915676e-05, "net_mass_tendency_due_to_nudging": 4.8848740795206825e-08, "storage_of_specific_humidity_path_due_to_python": -5.257486051249621e-07, "storage_of_total_water_path_due_to_python": -5.262175561647384e-07, "storage_of_mass_due_to_python": -4.69270527920973e-06}
INFO:statistics:{"time": "2016-08-01T00:30:00", "storage_of_specific_humidity_path_due_to_microphysics": 3.514122620263514e-05, "evaporation": 3.556450552870381e-05, "cnvprcp_after_physics": 1.404243820461793e-05, "total_precip_after_physics": 1.5856664030241084e-05, "storage_of_specific_humidity_path_due_to_fv3_physics": 4.274285681870165e-05, "storage_of_total_water_path_due_to_fv3_physics": 1.843891007951917e-05, "storage_of_mass_due_to_fv3_physics": 0.00018088570788009033, "surface_temperature_reference": 290.1222061181736, "area": 38505756482.50796, "cnvprcp_after_python": 1.404243820461793e-05, "total_precip": 1.6508798317962014e-05, "net_moistening_due_to_nudging": -5.272274840053458e-07, "net_heating_due_to_nudging": 2.033826632857872, "water_vapor_path": 27.468113049104364, "physics_precip": 1.761851558915676e-05, "net_mass_tendency_due_to_nudging": 4.8848740795206825e-08, "storage_of_specific_humidity_path_due_to_python": -5.257486051249621e-07, "storage_of_total_water_path_due_to_python": -5.262175561647384e-07, "storage_of_mass_due_to_python": -4.69270527920973e-06}
DEBUG:runtime.steppers.base:Dynamics Step
DEBUG:runtime.steppers.base:Physics Step (compute)
DEBUG:runtime.steppers.base:Physics Step (apply)

WARNING from PE     0: diag_util_mod::opening_file: module/field_name (dynamics/w50) NOT registered


WARNING from PE     0: diag_util_mod::opening_file: module/field_name (dynamics/w50) NOT registered

 ---isec,seconds         900        1800
  gfs diags time since last bucket empty:   0.25000000000000000      hrs
DEBUG:runtime.steppers.base:Computing nudging tendencies
DEBUG:runtime.steppers.base:Getting state variables: ['air_temperature', 'pressure_thickness_of_atmospheric_layer', 'specific_humidity', 'x_wind', 'y_wind', 'total_precipitation', 'surface_precipitation_rate', 'pressure_thickness_of_atmospheric_layer']
DEBUG:runtime.steppers.base:Setting Fortran State
INFO:__main__:diags: ['storage_of_specific_humidity_path_due_to_microphysics', 'evaporation', 'cnvprcp_after_physics', 'total_precip_after_physics', 'tendency_of_specific_humidity_due_to_fv3_physics', 'tendency_of_air_temperature_due_to_fv3_physics', 'tendency_of_eastward_wind_due_to_fv3_physics', 'tendency_of_northward_wind_due_to_fv3_physics', 'storage_of_specific_humidity_path_due_to_fv3_physics', 'storage_of_total_water_path_due_to_fv3_physics', 'storage_of_mass_due_to_fv3_physics', 'air_temperature_reference', 'specific_humidity_reference', 'surface_temperature_reference', 'pressure_thickness_of_atmospheric_layer_reference', 'y_wind_reference', 'x_wind_reference', 'area', 'cnvprcp_after_python', 'total_precip', 'net_moistening_due_to_nudging', 'net_heating_due_to_nudging', 'water_vapor_path', 'physics_precip', 'net_mass_tendency_due_to_nudging', 'air_temperature_tendency_due_to_nudging', 'pressure_thickness_of_atmospheric_layer_tendency_due_to_nudging', 'specific_humidity_tendency_due_to_nudging', 'x_wind_tendency_due_to_nudging', 'y_wind_tendency_due_to_nudging', 'x_wind', 'y_wind', 'eastward_wind', 'northward_wind', 'vertical_wind', 'air_temperature', 'specific_humidity', 'pressure_thickness_of_atmospheric_layer', 'vertical_thickness_of_atmospheric_layer', 'land_sea_mask', 'surface_temperature', 'surface_geopotential', 'sensible_heat_flux', 'latent_heat_flux', 'total_precipitation', 'surface_precipitation_rate', 'total_soil_moisture', 'total_sky_downward_shortwave_flux_at_surface', 'total_sky_upward_shortwave_flux_at_surface', 'total_sky_downward_longwave_flux_at_surface', 'total_sky_upward_longwave_flux_at_surface', 'total_sky_downward_shortwave_flux_at_top_of_atmosphere', 'total_sky_upward_shortwave_flux_at_top_of_atmosphere', 'total_sky_upward_longwave_flux_at_top_of_atmosphere', 'clear_sky_downward_shortwave_flux_at_surface', 'clear_sky_upward_shortwave_flux_at_surface', 'clear_sky_downward_longwave_flux_at_surface', 'clear_sky_upward_longwave_flux_at_surface', 'clear_sky_upward_shortwave_flux_at_top_of_atmosphere', 'clear_sky_upward_longwave_flux_at_top_of_atmosphere', 'latitude', 'longitude', 'tendency_of_specific_humidity_due_to_python', 'tendency_of_air_temperature_due_to_python', 'tendency_of_eastward_wind_due_to_python', 'tendency_of_northward_wind_due_to_python', 'storage_of_specific_humidity_path_due_to_python', 'storage_of_total_water_path_due_to_python', 'storage_of_mass_due_to_python']
INFO:statistics:{"time": "2016-08-01T00:45:00", "storage_of_specific_humidity_path_due_to_microphysics": 1.0643047143634675e-05, "evaporation": 3.300628276757381e-05, "cnvprcp_after_physics": 3.0112246367776673e-05, "total_precip_after_physics": 1.796662117414463e-05, "storage_of_specific_humidity_path_due_to_fv3_physics": 1.2168808282465027e-05, "storage_of_total_water_path_due_to_fv3_physics": 1.350206716867418e-05, "storage_of_mass_due_to_fv3_physics": 0.0001324552789246989, "surface_temperature_reference": 290.11307209786986, "area": 38505756482.50796, "cnvprcp_after_python": 3.0112246367776673e-05, "total_precip": 1.8779755472183984e-05, "net_moistening_due_to_nudging": -4.031729626193724e-07, "net_heating_due_to_nudging": 1.2220623759976357, "water_vapor_path": 27.478590927437892, "physics_precip": 1.9962912415716257e-05, "net_mass_tendency_due_to_nudging": 2.1051832411662695e-07, "storage_of_specific_humidity_path_due_to_python": -3.993026168191198e-07, "storage_of_total_water_path_due_to_python": -4.000995943448807e-07, "storage_of_mass_due_to_python": -1.8897034467934902e-06}
INFO:statistics:{"time": "2016-08-01T00:45:00", "storage_of_specific_humidity_path_due_to_microphysics": 1.0643047143634675e-05, "evaporation": 3.300628276757381e-05, "cnvprcp_after_physics": 3.0112246367776673e-05, "total_precip_after_physics": 1.796662117414463e-05, "storage_of_specific_humidity_path_due_to_fv3_physics": 1.2168808282465027e-05, "storage_of_total_water_path_due_to_fv3_physics": 1.350206716867418e-05, "storage_of_mass_due_to_fv3_physics": 0.0001324552789246989, "surface_temperature_reference": 290.11307209786986, "area": 38505756482.50796, "cnvprcp_after_python": 3.0112246367776673e-05, "total_precip": 1.8779755472183984e-05, "net_moistening_due_to_nudging": -4.031729626193724e-07, "net_heating_due_to_nudging": 1.2220623759976357, "water_vapor_path": 27.478590927437892, "physics_precip": 1.9962912415716257e-05, "net_mass_tendency_due_to_nudging": 2.1051832411662695e-07, "storage_of_specific_humidity_path_due_to_python": -3.993026168191198e-07, "storage_of_total_water_path_due_to_python": -4.000995943448807e-07, "storage_of_mass_due_to_python": -1.8897034467934902e-06}
Traceback (most recent call last):
  File "sklearn_runfile.py", line 60, in <module>
    diag_file.observe(time, diagnostics)
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 234, in observe
    self.flush()
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 267, in flush
    self._monitor.store(quantities)
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 107, in store
    self._writers[name].append(quantity)  # type: ignore[index]
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 192, in append
    raise err
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 187, in append
    self.array[target_slice] = quantity.view[:][from_slice]
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1115, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1210, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1501, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1529, in _set_selection
    check_array_shape('value', value, sel_shape)
  File "/usr/local/lib/python3.6/dist-packages/zarr/util.py", line 505, in check_array_shape
    .format(param, shape, array.shape))
ValueError: parameter 'value': expected array with shape (79, 48, 49), got (79, 48, 48)
Traceback (most recent call last):
  File "sklearn_runfile.py", line 60, in <module>
    diag_file.observe(time, diagnostics)
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 234, in observe
    self.flush()
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 267, in flush
    self._monitor.store(quantities)
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 107, in store
    self._writers[name].append(quantity)  # type: ignore[index]
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 192, in append
    raise err
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 187, in append
    self.array[target_slice] = quantity.view[:][from_slice]
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1115, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1210, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1501, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1529, in _set_selection
    check_array_shape('value', value, sel_shape)
  File "/usr/local/lib/python3.6/dist-packages/zarr/util.py", line 505, in check_array_shape
    .format(param, shape, array.shape))
ValueError: parameter 'value': expected array with shape (79, 48, 49), got (79, 48, 48)
Traceback (most recent call last):
  File "sklearn_runfile.py", line 60, in <module>
    diag_file.observe(time, diagnostics)
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 234, in observe
    self.flush()
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 267, in flush
    self._monitor.store(quantities)
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 107, in store
    self._writers[name].append(quantity)  # type: ignore[index]
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 192, in append
    raise err
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 187, in append
    self.array[target_slice] = quantity.view[:][from_slice]
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1115, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1210, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1501, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1529, in _set_selection
    check_array_shape('value', value, sel_shape)
  File "/usr/local/lib/python3.6/dist-packages/zarr/util.py", line 505, in check_array_shape
    .format(param, shape, array.shape))
ValueError: parameter 'value': expected array with shape (79, 48, 49), got (79, 48, 48)
Traceback (most recent call last):
  File "sklearn_runfile.py", line 60, in <module>
    diag_file.observe(time, diagnostics)
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 234, in observe
    self.flush()
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 267, in flush
    self._monitor.store(quantities)
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 107, in store
    self._writers[name].append(quantity)  # type: ignore[index]
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 192, in append
    raise err
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 187, in append
    self.array[target_slice] = quantity.view[:][from_slice]
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1115, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1210, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1501, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1529, in _set_selection
    check_array_shape('value', value, sel_shape)
  File "/usr/local/lib/python3.6/dist-packages/zarr/util.py", line 505, in check_array_shape
    .format(param, shape, array.shape))
ValueError: parameter 'value': expected array with shape (79, 48, 49), got (79, 48, 48)
Traceback (most recent call last):
  File "sklearn_runfile.py", line 60, in <module>
    diag_file.observe(time, diagnostics)
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 234, in observe
    self.flush()
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 267, in flush
    self._monitor.store(quantities)
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 107, in store
    self._writers[name].append(quantity)  # type: ignore[index]
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 192, in append
    raise err
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/zarr_monitor.py", line 187, in append
    self.array[target_slice] = quantity.view[:][from_slice]
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1115, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1210, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1501, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "/usr/local/lib/python3.6/dist-packages/zarr/core.py", line 1529, in _set_selection
    check_array_shape('value', value, sel_shape)
  File "/usr/local/lib/python3.6/dist-packages/zarr/util.py", line 505, in check_array_shape
    .format(param, shape, array.shape))
ValueError: parameter 'value': expected array with shape (79, 48, 49), got (79, 48, 48)

**Comment by brianhenn** [comment]
Resolved by https://github.com/VulcanClimateModeling/fv3gfs-util/pull/60
